//! The TypeScript bindings for the types that cross the IPC boundary, and the
//! drift check that keeps them honest.
//!
//! Rust is the source of truth for every type here. The frontend used to carry
//! a hand-written mirror of each — 255 of them across the `src/ipc/` modules —
//! and nothing compared the two, so a renamed Rust field became a runtime
//! `undefined` in the renderer with no failing test anywhere.
//!
//! Run with `UPDATE_BINDINGS=1` to regenerate; without it the test compares
//! against the committed file and fails when Rust changed without
//! regeneration. That failure is the point: it is the test the mirrors never
//! had.
//!
//! This is the first slice of the migration. The remaining crates get their
//! derives and join this list as they are converted; a type is either
//! generated or hand-written, never both, so there is one source of truth at
//! every step.

use std::path::PathBuf;

/// Every type in this crate that a command sends or receives.
fn bindings() -> Result<String, Box<dyn std::error::Error>> {
    use specta::ts::{ExportConfiguration, export};
    use std::collections::BTreeMap;

    let config = ExportConfiguration::new().bigint(specta::ts::BigIntExportBehavior::Number);

    // `export::<T>` emits T *and* everything it references, so exporting each
    // type in turn repeats the shared ones (`Head` sits inside several).
    // Collect by declaration name instead of concatenating.
    let mut declarations: BTreeMap<String, String> = BTreeMap::new();
    let mut exports = Vec::new();

    macro_rules! emit {
        ($($t:ty),+ $(,)?) => {{
            $(
                exports.push((stringify!($t), export::<$t>(&config)?));
            )+
        }};
    }
    emit!(
        wns_kernel::CoreError,
        wns_kernel::Head,
        wns_kernel::ProjectAccess,
        wns_kernel::Revision,
        wns_kernel::ProjectInfo,
        wns_kernel::DocumentRecord,
        wns_kernel::DocumentRole,
        wns_kernel::RestoredDecision,
        wns_kernel::AppliedDecision,
        wns_kernel::StoredResult,
        wns_kernel::SnapshotReceipt,
    );

    for (_, text) in &exports {
        for block in split_declarations(text) {
            match declaration_name(&block) {
                Some(name) => { declarations.entry(name).or_insert(block); }
                None => {}
            }
        }
    }

    let mut out = String::from(
        "// Generated by `cargo test -p wns-kernel --test bindings` with UPDATE_BINDINGS=1.\n\
         // Do not edit: change the Rust type and regenerate.\n\n",
    );
    for block in declarations.values() {
        out.push_str(block.trim_end());
        out.push_str("\n\n");
    }
    Ok(out)
}

/// One `export type X = …;` (or `export enum`) per element.
fn split_declarations(text: &str) -> Vec<String> {
    let mut blocks = Vec::new();
    let mut current = String::new();
    for line in text.lines() {
        // A declaration starts at `export`, and a doc comment starts the block
        // it belongs to. Requiring the block to already hold a declaration
        // keeps a leading comment attached to the type below it instead of
        // becoming a block of its own.
        let starts_item = line.starts_with("export ") || line.starts_with("/**");
        if starts_item && current.contains("export ") {
            blocks.push(std::mem::take(&mut current));
        }
        current.push_str(line);
        current.push('\n');
    }
    if !current.trim().is_empty() {
        blocks.push(current);
    }
    blocks
}

fn declaration_name(block: &str) -> Option<String> {
    // specta emits a doc comment above the declaration; skip to the `export`.
    let start = block.find("export ")?;
    let rest = block[start..].strip_prefix("export ")?;
    let rest = rest
        .strip_prefix("type ")
        .or_else(|| rest.strip_prefix("enum "))
        .or_else(|| rest.strip_prefix("interface "))?;
    let end = rest
        .find(|c: char| !(c.is_alphanumeric() || c == '_'))
        .unwrap_or(rest.len());
    Some(rest[..end].to_owned())
}

fn target() -> PathBuf {
    // crates/kernel -> crates -> root
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../apps/desktop/src/ipc/generated/kernel.ts")
}

#[test]
fn generated_bindings_match_the_rust_types() {
    let generated = bindings().expect("generate bindings");
    let path = target();
    if std::env::var_os("UPDATE_BINDINGS").is_some() {
        std::fs::create_dir_all(path.parent().unwrap()).expect("create generated directory");
        std::fs::write(&path, &generated).expect("write bindings");
        eprintln!("wrote {}", path.display());
        return;
    }
    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    assert_eq!(
        committed,
        generated,
        "{} is stale. Rust is the source of truth: regenerate with \
         `UPDATE_BINDINGS=1 cargo test -p wns-kernel --test bindings` and commit the result.",
        path.display()
    );
}
