[package]
name = "webnovel-desktop"
version.workspace = true
edition.workspace = true

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
tauri = { version = "=2.11.5", features = [] }
serde = { version = "=1.0.229", features = ["derive"] }
webnovel-core = { path = "../../../crates/core" }

[features]
custom-protocol = ["tauri/custom-protocol"]
