//! Per-user provider credentials backed by the Windows Credential Manager.
//!
//! Credential values deliberately have no serde or `Debug` representation.
//! The persistent reference is an opaque, app-owned UUID target; the target
//! is safe to keep in app settings while the secret remains in the OS store.

use crate::projects::{CoreError, CoreResult};
use std::fmt;
use uuid::Uuid;

/// Windows' documented generic credential blob limit is 5 KiB. Keep the same
/// bound on every platform so profile validation does not differ by target.
pub const MAX_CREDENTIAL_BYTES: usize = 5 * 1024;
const TARGET_PREFIX: &str = "WebnovelStudioV3/Profile/";

/// An app-owned, nonsecret reference to one OS credential.
///
/// References are intentionally generated by [`CredentialStore::write_new`]
/// and can only be reopened when they have the exact canonical UUID form.
#[derive(Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CredentialTarget(String);

impl CredentialTarget {
    /// Parse a previously persisted target without touching the OS store.
    pub fn parse(value: &str) -> CoreResult<Self> {
        let Some(uuid) = value.strip_prefix(TARGET_PREFIX) else {
            return Err(invalid_target());
        };
        let parsed = Uuid::parse_str(uuid).map_err(|_| invalid_target())?;
        if parsed.to_string() != uuid {
            return Err(invalid_target());
        }
        Ok(Self(value.to_owned()))
    }

    fn generate() -> Self {
        Self(format!("{TARGET_PREFIX}{}", Uuid::new_v4()))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for CredentialTarget {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_tuple("CredentialTarget")
            .field(&self.0)
            .finish()
    }
}

fn invalid_target() -> CoreError {
    CoreError::new(
        "InvalidCredentialTarget",
        "The provider credential reference is not an app-owned target.",
    )
}

fn validate_secret(secret: &[u8]) -> CoreResult<()> {
    if secret.is_empty() {
        return Err(CoreError::new(
            "InvalidCredential",
            "The provider credential cannot be empty.",
        ));
    }
    if secret.len() > MAX_CREDENTIAL_BYTES {
        return Err(CoreError::new(
            "CredentialTooLarge",
            "The provider credential exceeds the supported size.",
        ));
    }
    Ok(())
}

/// An in-memory credential value with redacted diagnostics and best-effort
/// zeroization when its owner releases it.
pub struct SecretValue(Vec<u8>);

impl SecretValue {
    /// Validate and own a secret for a provider construction boundary.
    ///
    /// The value remains deliberately non-serializable and redacts its debug
    /// representation; callers should drop it as soon as the provider has
    /// copied the secret into its private request configuration.
    pub fn new(mut bytes: Vec<u8>) -> CoreResult<Self> {
        if let Err(error) = validate_secret(&bytes) {
            wipe_bytes(&mut bytes);
            return Err(error);
        }
        Ok(Self(bytes))
    }

    /// Borrow the secret only for the immediate provider-construction step.
    /// Callers must not persist, serialize, or log the returned bytes.
    pub fn expose_bytes(&self) -> &[u8] {
        &self.0
    }
}

impl fmt::Debug for SecretValue {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("[REDACTED]")
    }
}

impl Drop for SecretValue {
    fn drop(&mut self) {
        wipe_bytes(&mut self.0);
    }
}

/// Secret storage required by provider setup and dispatch.
///
/// `write_new` never overwrites an existing target. Profile updates therefore
/// publish a new reference only after its credential has been stored, allowing
/// requests that already captured an older profile to finish with the older
/// route and key.
pub trait CredentialStore: Send + Sync {
    fn read(&self, target: &CredentialTarget) -> CoreResult<Option<SecretValue>>;
    fn write_new(&self, secret: &[u8]) -> CoreResult<CredentialTarget>;
    fn delete(&self, target: &CredentialTarget) -> CoreResult<()>;
}

#[cfg(windows)]
#[derive(Debug, Default, Clone, Copy)]
pub struct WindowsCredentialStore;

#[cfg(windows)]
impl CredentialStore for WindowsCredentialStore {
    fn read(&self, target: &CredentialTarget) -> CoreResult<Option<SecretValue>> {
        use std::ptr;
        use windows_sys::Win32::Foundation::{ERROR_NOT_FOUND, GetLastError};
        use windows_sys::Win32::Security::Credentials::{
            CRED_TYPE_GENERIC, CREDENTIALW, CredFree, CredReadW,
        };

        let target_wide = wide_target(target);
        let mut credential: *mut CREDENTIALW = ptr::null_mut();
        let read =
            unsafe { CredReadW(target_wide.as_ptr(), CRED_TYPE_GENERIC, 0, &mut credential) };
        if read == 0 {
            let code = unsafe { GetLastError() };
            if code == ERROR_NOT_FOUND {
                return Ok(None);
            }
            return Err(store_error("The Windows credential could not be read."));
        }
        if credential.is_null() {
            return Err(store_error(
                "The Windows credential store returned no credential.",
            ));
        }

        let result = unsafe {
            let value = &*credential;
            let size = usize::try_from(value.CredentialBlobSize).unwrap_or(usize::MAX);
            if size > MAX_CREDENTIAL_BYTES || (size > 0 && value.CredentialBlob.is_null()) {
                Err(store_error("The stored provider credential is invalid."))
            } else if size == 0 {
                Err(CoreError::new(
                    "InvalidCredential",
                    "The stored provider credential is empty.",
                ))
            } else {
                SecretValue::new(std::slice::from_raw_parts(value.CredentialBlob, size).to_vec())
                    .map(Some)
            }
        };
        unsafe { CredFree(credential.cast()) };
        result
    }

    fn write_new(&self, secret: &[u8]) -> CoreResult<CredentialTarget> {
        use windows_sys::Win32::Security::Credentials::{
            CRED_PERSIST_LOCAL_MACHINE, CRED_TYPE_GENERIC, CREDENTIALW, CredWriteW,
        };

        validate_secret(secret)?;
        let target = CredentialTarget::generate();
        let target_wide = wide_target(&target);
        let mut blob = secret.to_vec();
        let credential = CREDENTIALW {
            Type: CRED_TYPE_GENERIC,
            TargetName: target_wide.as_ptr().cast_mut(),
            CredentialBlobSize: u32::try_from(blob.len()).expect("bounded credential size"),
            CredentialBlob: blob.as_mut_ptr(),
            Persist: CRED_PERSIST_LOCAL_MACHINE,
            ..Default::default()
        };
        let written = unsafe { CredWriteW(&credential, 0) };
        wipe_bytes(&mut blob);
        if written == 0 {
            return Err(store_error("The Windows credential could not be stored."));
        }
        Ok(target)
    }

    fn delete(&self, target: &CredentialTarget) -> CoreResult<()> {
        use windows_sys::Win32::Foundation::{ERROR_NOT_FOUND, GetLastError};
        use windows_sys::Win32::Security::Credentials::{CRED_TYPE_GENERIC, CredDeleteW};

        let target_wide = wide_target(target);
        let deleted = unsafe { CredDeleteW(target_wide.as_ptr(), CRED_TYPE_GENERIC, 0) };
        if deleted != 0 {
            return Ok(());
        }
        let code = unsafe { GetLastError() };
        if code == ERROR_NOT_FOUND {
            Ok(())
        } else {
            Err(store_error("The Windows credential could not be deleted."))
        }
    }
}

#[cfg(windows)]
fn wide_target(target: &CredentialTarget) -> Vec<u16> {
    target.0.encode_utf16().chain(std::iter::once(0)).collect()
}

#[cfg(windows)]
fn store_error(detail: &str) -> CoreError {
    CoreError::new("CredentialStoreUnavailable", detail)
}

#[cfg(not(windows))]
#[derive(Debug, Default, Clone, Copy)]
pub struct WindowsCredentialStore;

#[cfg(not(windows))]
impl CredentialStore for WindowsCredentialStore {
    fn read(&self, _target: &CredentialTarget) -> CoreResult<Option<SecretValue>> {
        Err(CoreError::new(
            "CredentialStoreUnavailable",
            "Secure provider credentials are currently available on Windows only.",
        ))
    }

    fn write_new(&self, _secret: &[u8]) -> CoreResult<CredentialTarget> {
        Err(CoreError::new(
            "CredentialStoreUnavailable",
            "Secure provider credentials are currently available on Windows only.",
        ))
    }

    fn delete(&self, _target: &CredentialTarget) -> CoreResult<()> {
        Err(CoreError::new(
            "CredentialStoreUnavailable",
            "Secure provider credentials are currently available on Windows only.",
        ))
    }
}

fn wipe_bytes(bytes: &mut [u8]) {
    for byte in bytes {
        // Volatile writes prevent the compiler from removing this best-effort
        // cleanup of transient credential buffers.
        unsafe { std::ptr::write_volatile(byte, 0) };
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;
    use std::sync::Mutex;

    #[derive(Default)]
    struct InMemoryCredentialStore {
        values: Mutex<HashMap<CredentialTarget, Vec<u8>>>,
    }

    impl fmt::Debug for InMemoryCredentialStore {
        fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
            let count = self.values.lock().map(|values| values.len()).unwrap_or(0);
            formatter
                .debug_struct("InMemoryCredentialStore")
                .field("credential_count", &count)
                .finish()
        }
    }

    impl CredentialStore for InMemoryCredentialStore {
        fn read(&self, target: &CredentialTarget) -> CoreResult<Option<SecretValue>> {
            let values = self.values.lock().map_err(|_| {
                CoreError::new(
                    "CredentialStoreUnavailable",
                    "The credential store is unavailable.",
                )
            })?;
            values
                .get(target)
                .map(|secret| SecretValue::new(secret.clone()))
                .transpose()
        }

        fn write_new(&self, secret: &[u8]) -> CoreResult<CredentialTarget> {
            validate_secret(secret)?;
            let target = CredentialTarget::generate();
            self.values
                .lock()
                .map_err(|_| {
                    CoreError::new(
                        "CredentialStoreUnavailable",
                        "The credential store is unavailable.",
                    )
                })?
                .insert(target.clone(), secret.to_vec());
            Ok(target)
        }

        fn delete(&self, target: &CredentialTarget) -> CoreResult<()> {
            let mut values = self.values.lock().map_err(|_| {
                CoreError::new(
                    "CredentialStoreUnavailable",
                    "The credential store is unavailable.",
                )
            })?;
            if let Some(mut secret) = values.remove(target) {
                wipe_bytes(&mut secret);
            }
            Ok(())
        }
    }

    #[test]
    fn generated_targets_are_canonical_and_owned() {
        let store = InMemoryCredentialStore::default();
        let first = store.write_new(b"sentinel-one").unwrap();
        assert!(first.as_str().starts_with(TARGET_PREFIX));
        assert_eq!(CredentialTarget::parse(first.as_str()).unwrap(), first);
        assert!(
            CredentialTarget::parse("other-app/Profile/00000000-0000-0000-0000-000000000000")
                .is_err()
        );
        assert!(
            CredentialTarget::parse(
                "WebnovelStudioV3/Profile/{00000000-0000-0000-0000-000000000000}"
            )
            .is_err()
        );
    }

    #[test]
    fn write_new_never_overwrites_and_delete_is_idempotent() {
        let store = InMemoryCredentialStore::default();
        let first = store.write_new(b"sentinel-one").unwrap();
        let second = store.write_new(b"sentinel-two").unwrap();
        assert_ne!(first, second);
        assert_eq!(
            store.read(&first).unwrap().unwrap().expose_bytes(),
            b"sentinel-one"
        );
        assert_eq!(
            store.read(&second).unwrap().unwrap().expose_bytes(),
            b"sentinel-two"
        );
        store.delete(&first).unwrap();
        store.delete(&first).unwrap();
        assert!(store.read(&first).unwrap().is_none());
        assert_eq!(
            store.read(&second).unwrap().unwrap().expose_bytes(),
            b"sentinel-two"
        );
    }

    #[test]
    fn secret_bounds_and_debug_redaction_hold() {
        let store = InMemoryCredentialStore::default();
        assert_eq!(store.write_new(&[]).unwrap_err().code, "InvalidCredential");
        assert_eq!(
            store
                .write_new(&vec![b'x'; MAX_CREDENTIAL_BYTES + 1])
                .unwrap_err()
                .code,
            "CredentialTooLarge"
        );
        let _target = store.write_new(b"sentinel-secret").unwrap();
        let debug = format!("{store:?}");
        assert!(!debug.contains("sentinel-secret"));
        assert!(!debug.contains("sentinel"));
    }

    #[test]
    fn secret_value_is_redacted_and_empty_stored_values_fail_closed() {
        let store = InMemoryCredentialStore::default();
        let target = CredentialTarget::generate();
        store
            .values
            .lock()
            .unwrap()
            .insert(target.clone(), Vec::new());
        assert_eq!(store.read(&target).unwrap_err().code, "InvalidCredential");
        let target = store.write_new(b"sentinel-secret").unwrap();
        let secret = store.read(&target).unwrap().unwrap();
        assert_eq!(format!("{secret:?}"), "[REDACTED]");
        assert!(!format!("{secret:?}").contains("sentinel"));
    }

    #[test]
    fn nonsecret_target_does_not_serialize_as_a_credential_value() {
        let store = InMemoryCredentialStore::default();
        let target = store.write_new(b"sentinel-secret").unwrap();
        let target_debug = format!("{target:?}");
        assert!(!target_debug.contains("sentinel-secret"));
        assert!(target_debug.contains(TARGET_PREFIX));
    }
}
